### ISSUE TITLE
Кнопка "Копировать в буфер обмена" на сайте

### ISSUE THREAD

**Issue by AnatolyRugalev** [bakwc/Pastexen#83]
Думаю, стоит запилить на сайте кнопку "Copy", которая будет копировать исходник в буфер (без номеров строк, RAW). Я понимаю, что есть кнопка RAW, но это (1)клик, (2)выделение всего и (3)копирование. Подсмотреть реализацию можно [здесь](http://www.colorzilla.com/gradient-editor/) в поле CSS.

**Comment by dakuenjery** [comment]
http://stackoverflow.com/questions/400212/how-do-i-copy-to-the-clipboard-in-javascript
надо попробывать

**Comment by bakwc** [comment]
дык тот вариант только для ie - для остальных браузеров флеш

**Comment by dakuenjery** [comment]
http://stackoverflow.com/a/30810322
у меня в хроме все работает

**Comment by bakwc** [comment]
прикольно, попробую

**Comment by eskrano** [comment]
Есть вариант чтоб поменьше кода было для кнопки "копировать"?

**Comment by bakwc** [comment]
http://stackoverflow.com/a/30810322 - у меня в firefox на macos не работает
http://steamdev.com/zclip/ - можно попробовать это, пока флеш не выпилили

**Comment by bakwc** [comment]
Хотя лучше ещё немного подождать и воткнуть решение dakuenjery - похоже в firefox-е в сентябре появится поддержка document.execCommand('copy')

**Comment by eskrano** [comment]
У меня работает на Firefox Dev.ed. document.execCommand('copy') .

**Comment by bakwc** [comment]
ок, его и воткнём как firefox зарелизится

**Comment by bakwc** [comment]
Запилил кнопку, просьба проверить - работает ли в вашем браузере.
